[Variables]

; ----------------------------
; Clock Settings
; ----------------------------

; If trying to change size, change the scale, not font size.
ClockScale=1.8

ClockFont="Universal Serif"
ClockFontSize=110
ClockFontColor=255,255,255

; ----------------------------
; General Dock Settings
; ----------------------------

DockScale=1.0

TrunicFont="Tunic"
EnglishFont="Odin Rounded"
TrunicFontSize=60
EnglishFontSize=50
TrunicFontColor=255,255,255,255
SpaceBetweenApps=125

; ----------------------------
; IMPORTANT NOTE
; To get Trunic Text, we use the Trunic font at https://github.com/dirdam/fonts/tree/main/tunic
; Use the README in that repository to help figure out the english text.
; ----------------------------

; ----------------------------
; App 1
; ----------------------------
App1FontColor=255,238,140,255
App1TrunicText="files"
App1EnglishText="Files"
App1Action="C:\Windows\explorer.exe"
App1Sound="#@#Sounds\files.wav"

; ----------------------------
; App 2
; ----------------------------
App2FontColor=119,211,119,255
App2TrunicText="placeholder"
App2EnglishText="placeholder"
App2Action=
App2Sound=

; ----------------------------
; App 3
; ----------------------------
App3FontColor=186,187,241,255
App3TrunicText="placeholder"
App3EnglishText="placeholder"
App3Action=
App3Sound=

; ----------------------------
; App 4
; ----------------------------
App4FontColor=179,235,242,255
App4TrunicText="placeholder"
App4EnglishText="placeholder"
App4Action=
App4Sound=

; ----------------------------
; App 5
; ----------------------------
App5FontColor=255,105,97,255
App5TrunicText="placeholder"
App5EnglishText="placeholder"
App5Action=
App5Sound=

; ----------------------------
; App 6
; ----------------------------
App6FontColor=244,184,228,255
App6TrunicText="placeholder"
App6EnglishText="placeholder"
App6Action=
App6Sound=