[Variables]

; ----------------------------
; Clock Settings
; ----------------------------

; If trying to change size, change the scale, not font size.
Scale=1.8

ClockFont="Universal Serif"
ClockFontSize=110
ClockFontColor=255,255,255

; ----------------------------
; General Dock Settings
; ----------------------------
TrunicFont="Tunic"
EnglishFont="Odin Rounded"
TrunicFontSize=60
EnglishFontSize=50
TrunicFontColor=255,255,255,255
SpaceBetweenApps=125

; ----------------------------
; IMPORTANT NOTE
; To get Trunic Text, we use the Trunic font at https://github.com/dirdam/fonts/tree/main/tunic
; Use the README in that repository to help figure out the english text.
; ----------------------------

; ----------------------------
; App 1
; ----------------------------
App1FontColor=255,105,97,255
App1TrunicText="cope ra"
App1EnglishText="Opera"
App1Action=
App1Sound=

; ----------------------------
; App 2
; ----------------------------
App2FontColor=119,211,119,255
App2TrunicText="spatifi"
App2EnglishText="Spotify"
App2Action=
App2Sound=

; ----------------------------
; App 3
; ----------------------------
App3FontColor=186,187,241,255
App3TrunicText="diskord"
App3EnglishText="Discord"
App3Action=
App3Sound=

; ----------------------------
; App 4
; ----------------------------
App4FontColor=179,235,242,255
App4TrunicText="steim"
App4EnglishText="Steam"
App4Action=
App4Sound=

; ----------------------------
; App 5
; ----------------------------
App5FontColor=255,238,140,255
App5TrunicText="files"
App5EnglishText="Files"
App5Action="C:\Windows\explorer.exe"
App5Sound="#@#Sounds\files.wav"

; ----------------------------
; App 6
; ----------------------------
App6FontColor=244,184,228,255
App6TrunicText="gaemes"
App6EnglishText="Games"
App6Action=
App6Sound=